#Docker-compose installation

sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

sample dokcer-compose file --> 


version: '3'
services:
 sample1:
  image: httpd
  ports:
  - "5000:5000"
 sample2:
  image: nginx
  
  
+++++++++++++++++++++++++++++++++++++++++++++++

sample web application yaml

version: '3.3'
services:
 db:
  image: mysql:5.7
  volumes:
  - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: somewordpress
   MYSQL_DATABASE: wordpress
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: wordpress
 wordpress:
  depends_on:
  - db
  image: wordpress:latest
  ports:
  - "8000:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: wordpress
   WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data:
